name: kitchen_helper
description: App intended to help owner of autonomous kitchens to calculate their expenses and profits.

publish_to: "none"

version: 1.3.6+15

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.3.0
  fpdart: ^0.0.12
  synchronized: ^3.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.7
  equatable: ^2.0.3
  flutter_modular: ^4.2.0
  bloc: ^8.0.1
  flutter_slidable: ^1.1.0
  multi_value_listenable_builder: ^0.0.2
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0
  auto_size_text: ^3.0.0
  device_preview: ^1.0.0
  sqflite_common_ffi: ^2.1.0+2
  build_runner: ^2.1.7
  dio: ^4.0.4
  firebase_crashlytics: ^2.5.2
  firebase_core: ^1.13.0
  device_info_plus: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  code_coverage: ^1.4.0
  json_serializable: ^6.0.1
  mocktail: ^0.2.0
  bloc_test: ^9.0.1
  modular_test: ^1.0.1+1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/splash_icon.png

flutter_icons:
  android: true
  image_path: "assets/splash_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/splash_icon.png"

flutter_native_splash:
  color: "#2196F3"
  image: "assets/splash_icon.png"
